'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { motion, AnimatePresence } from 'framer-motion'
import { useDropzone } from 'react-dropzone'
import {
  ArrowLeft,
  Download,
  FileText,
  Image as ImageIcon,
  FileArchive,
  Upload,
  Lock,
  Zap,
  AlertTriangle,
  ChevronRight,
  Loader2,
} from 'lucide-react'
import { toast } from 'sonner'
import { invoicesApi, escalationsApi } from '@/lib/api'
import type { Invoice, EvidenceItem, EscalationEvent } from '@/lib/types'
import { formatCurrency, formatDate, daysSince, STAGE_LABELS, STAGE_COLORS, cn } from '@/lib/utils'
import { StatusBadge } from '@/components/shared/status-badge'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
} from '@/components/ui/dialog'

// ─── Stage ordering for "next stage" suggestion ──────────────────────────────

const STAGE_ORDER = [
  'polite_reminder',
  'firm_notice',
  'final_warning',
  'legal_demand',
  'legal_action',
] as const

function nextStage(current: Invoice['escalationStage']) {
  if (!current) return 'polite_reminder'
  const idx = STAGE_ORDER.indexOf(current)
  return idx < STAGE_ORDER.length - 1 ? STAGE_ORDER[idx + 1] : null
}

// ─── File type icon ───────────────────────────────────────────────────────────

function FileIcon({ fileType }: { fileType: string }) {
  if (fileType.startsWith('image/'))
    return <ImageIcon className="h-5 w-5 text-violet-500" />
  if (fileType === 'application/pdf')
    return <FileText className="h-5 w-5 text-red-500" />
  return <FileArchive className="h-5 w-5 text-slate-400" />
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

// ─── Section fade animation ───────────────────────────────────────────────────

const sectionVariants = {
  hidden: { opacity: 0, y: 14 },
  visible: (delay: number) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.28, ease: 'easeOut', delay },
  }),
}

const evidenceItemVariants = {
  hidden: { opacity: 0, x: -10 },
  visible: { opacity: 1, x: 0, transition: { duration: 0.22, ease: 'easeOut' } },
}

// ─── Escalation email preview dialog ─────────────────────────────────────────

interface EscalationPreviewDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  event: EscalationEvent | null
  onSend: () => Promise<void>
}

function EscalationPreviewDialog({
  open,
  onOpenChange,
  event,
  onSend,
}: EscalationPreviewDialogProps) {
  const [sending, setSending] = useState(false)

  async function handleSend() {
    setSending(true)
    try {
      await onSend()
      onOpenChange(false)
    } finally {
      setSending(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Escalation Email Preview</DialogTitle>
        </DialogHeader>
        {event ? (
          <div className="px-6 pb-2 space-y-4">
            <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 space-y-2">
              <div className="flex items-start gap-2 text-sm">
                <span className="font-semibold text-slate-500 w-16 flex-shrink-0">Subject:</span>
                <span className="text-slate-800">{event.emailSubject ?? '—'}</span>
              </div>
            </div>
            <div className="rounded-lg border border-slate-200 bg-white p-4">
              <pre className="whitespace-pre-wrap text-sm text-slate-700 font-sans leading-relaxed">
                {event.emailBody ?? 'No body generated.'}
              </pre>
            </div>
            {event.generatedByAi && (
              <p className="text-xs text-slate-400">
                Generated by AI
                {event.aiConfidenceScore !== null
                  ? ` · Confidence ${Math.round(event.aiConfidenceScore * 100)}%`
                  : ''}
              </p>
            )}
          </div>
        ) : (
          <div className="px-6 pb-4">
            <div className="h-40 animate-pulse rounded-lg bg-slate-100" />
          </div>
        )}
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={sending}>
            Cancel
          </Button>
          <Button onClick={handleSend} disabled={sending || !event}>
            {sending ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Sending…
              </>
            ) : (
              'Send Email'
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function InvoiceDetailPage() {
  const { id } = useParams<{ id: string }>()
  const router = useRouter()

  const [invoice, setInvoice] = useState<Invoice | null>(null)
  const [evidence, setEvidence] = useState<EvidenceItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const [uploading, setUploading] = useState(false)
  const [showLockedAnim, setShowLockedAnim] = useState(false)
  const prevEvidenceCount = useRef(0)

  const [escalationDraft, setEscalationDraft] = useState<EscalationEvent | null>(null)
  const [draftLoading, setDraftLoading] = useState(false)
  const [previewOpen, setPreviewOpen] = useState(false)

  async function loadInvoice() {
    if (!id) return
    setLoading(true)
    setError(null)
    try {
      const [inv, evList] = await Promise.all([
        invoicesApi.get(id),
        invoicesApi.getEvidence(id),
      ])
      setInvoice(inv)
      prevEvidenceCount.current = evList.length
      setEvidence(evList)
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to load invoice'
      setError(message)
      toast.error('Could not load invoice', { description: message })
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadInvoice()
  }, [id])

  // Dropzone
  const onDrop = useCallback(
    async (accepted: File[]) => {
      if (!id || accepted.length === 0) return
      const file = accepted[0]
      setUploading(true)
      const toastId = toast.loading(`Uploading ${file.name}…`)
      try {
        const newItem = await invoicesApi.uploadEvidence(id, file)
        toast.dismiss(toastId)
        toast.success('Evidence uploaded', { description: file.name })

        setEvidence((prev) => {
          const wasEmpty = prev.length === 0
          const next = [...prev, newItem]
          if (wasEmpty) setShowLockedAnim(true)
          return next
        })
      } catch (err) {
        toast.dismiss(toastId)
        const message = err instanceof Error ? err.message : 'Upload failed'
        toast.error('Upload failed', { description: message })
      } finally {
        setUploading(false)
      }
    },
    [id],
  )

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'image/*': [],
      'application/pdf': [],
      'text/*': [],
    },
    multiple: false,
    disabled: uploading,
  })

  async function handleEscalateNow() {
    if (!id) return
    setDraftLoading(true)
    try {
      const draft = await escalationsApi.draftEmail(id)
      setEscalationDraft(draft)
      setPreviewOpen(true)
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Draft generation failed'
      toast.error('Could not draft escalation', { description: message })
    } finally {
      setDraftLoading(false)
    }
  }

  async function handleSendEscalation() {
    if (!id) return
    await escalationsApi.sendEmail(id)
    toast.success('Escalation sent', {
      description: 'Bad Cop has dispatched the email on your behalf.',
    })
    await loadInvoice()
  }

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-8 w-40 animate-pulse rounded-md bg-slate-200" />
        <div className="h-36 w-full animate-pulse rounded-xl bg-slate-200" />
        <div className="grid grid-cols-4 gap-4">
          {[0, 1, 2, 3].map((i) => (
            <div key={i} className="h-20 animate-pulse rounded-xl bg-slate-200" />
          ))}
        </div>
      </div>
    )
  }

  if (error || !invoice) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center">
        <p className="text-base font-semibold text-slate-700">Invoice not found</p>
        <p className="mt-1 text-sm text-slate-500">{error ?? 'This invoice does not exist.'}</p>
        <Button variant="outline" className="mt-6" onClick={() => router.push('/invoices')}>
          <ArrowLeft className="h-4 w-4" /> Back to Invoices
        </Button>
      </div>
    )
  }

  const overdueDays = invoice.status !== 'paid' && invoice.status !== 'written_off'
    ? Math.max(daysSince(invoice.dueDate), 0)
    : 0
  const isOverdue = overdueDays > 0
  const suggestedNext = nextStage(invoice.escalationStage)

  return (
    <div className="space-y-8">
      {/* Back */}
      <motion.div custom={0} variants={sectionVariants} initial="hidden" animate="visible">
        <Button variant="ghost" size="sm" onClick={() => router.push('/invoices')}>
          <ArrowLeft className="h-4 w-4" />
          Back to Invoices
        </Button>
      </motion.div>

      {/* Header card */}
      <motion.div
        custom={0.05}
        variants={sectionVariants}
        initial="hidden"
        animate="visible"
        className="rounded-xl border border-slate-200 bg-white p-7"
      >
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-3 flex-wrap">
              <h1 className="text-2xl font-bold font-mono text-slate-900">
                {invoice.invoiceNumber}
              </h1>
              <StatusBadge status={invoice.status} />
              {isOverdue && (
                <span className="inline-flex items-center gap-1.5 rounded-full bg-red-100 px-3 py-0.5 text-sm font-semibold text-red-700">
                  <AlertTriangle className="h-3.5 w-3.5" />
                  {overdueDays}d overdue
                </span>
              )}
            </div>
            <p className="text-4xl font-extrabold text-slate-900 tabular-nums">
              {formatCurrency(invoice.amount, invoice.currency)}
            </p>
          </div>

          <Button
            onClick={handleEscalateNow}
            disabled={draftLoading}
            className="self-start"
          >
            {draftLoading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Drafting…
              </>
            ) : (
              <>
                <Zap className="h-4 w-4" />
                Escalate Now
              </>
            )}
          </Button>
        </div>
      </motion.div>

      {/* Info grid */}
      <motion.div
        custom={0.1}
        variants={sectionVariants}
        initial="hidden"
        animate="visible"
        className="grid grid-cols-2 gap-4 sm:grid-cols-4"
      >
        {[
          { label: 'Client', value: invoice.clientName ?? '—' },
          { label: 'Issue Date', value: formatDate(invoice.issueDate) },
          { label: 'Due Date', value: formatDate(invoice.dueDate) },
          { label: 'Currency', value: invoice.currency },
        ].map((item) => (
          <div
            key={item.label}
            className="rounded-xl border border-slate-200 bg-white p-4 space-y-1"
          >
            <p className="text-xs font-medium uppercase tracking-wide text-slate-500">
              {item.label}
            </p>
            <p className="text-sm font-semibold text-slate-900">{item.value}</p>
          </div>
        ))}
      </motion.div>

      {/* Escalation stage banner */}
      {(invoice.escalationStage || suggestedNext) && (
        <motion.div
          custom={0.15}
          variants={sectionVariants}
          initial="hidden"
          animate="visible"
          className={cn(
            'rounded-xl border p-5 flex items-start gap-4',
            invoice.escalationStage
              ? STAGE_COLORS[invoice.escalationStage]
              : 'border-slate-200 bg-slate-50 text-slate-700',
          )}
        >
          <Zap className="h-5 w-5 mt-0.5 flex-shrink-0" />
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold">
              {invoice.escalationStage
                ? `Current stage: ${STAGE_LABELS[invoice.escalationStage]}`
                : 'No escalation started yet'}
            </p>
            {suggestedNext && (
              <p className="mt-0.5 text-xs opacity-80 flex items-center gap-1">
                Next suggested:
                <ChevronRight className="h-3 w-3" />
                {STAGE_LABELS[suggestedNext]}
              </p>
            )}
          </div>
        </motion.div>
      )}

      {/* Line items */}
      {invoice.lineItems && invoice.lineItems.length > 0 && (
        <motion.div
          custom={0.18}
          variants={sectionVariants}
          initial="hidden"
          animate="visible"
          className="rounded-xl border border-slate-200 bg-white overflow-hidden"
        >
          <div className="px-6 py-4 border-b border-slate-200">
            <h2 className="text-base font-semibold text-slate-900">Line Items</h2>
          </div>
          <div className="grid grid-cols-[1fr_80px_120px_100px] text-xs font-semibold uppercase tracking-wide text-slate-500 bg-slate-50 px-6 py-2.5 border-b border-slate-100">
            <span>Description</span>
            <span>Qty</span>
            <span>Unit Price</span>
            <span className="text-right">Total</span>
          </div>
          {invoice.lineItems.map((item, i) => (
            <div
              key={i}
              className="grid grid-cols-[1fr_80px_120px_100px] px-6 py-3 border-b border-slate-100 last:border-0 items-center"
            >
              <span className="text-sm text-slate-700">{item.description}</span>
              <span className="text-sm text-slate-600 tabular-nums">{item.quantity}</span>
              <span className="text-sm text-slate-600 tabular-nums">
                {formatCurrency(item.unitPrice, invoice.currency)}
              </span>
              <span className="text-sm font-semibold text-slate-800 tabular-nums text-right">
                {formatCurrency(item.total, invoice.currency)}
              </span>
            </div>
          ))}
          <div className="flex justify-end px-6 py-3 border-t border-slate-200 bg-slate-50">
            <span className="text-sm font-bold text-slate-900">
              Total: {formatCurrency(invoice.amount, invoice.currency)}
            </span>
          </div>
        </motion.div>
      )}

      {/* Evidence Locker */}
      <motion.div
        custom={0.2}
        variants={sectionVariants}
        initial="hidden"
        animate="visible"
        className="rounded-xl border border-slate-200 bg-white overflow-hidden"
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <div className="flex items-center gap-2">
            <Lock className="h-4 w-4 text-slate-500" />
            <h2 className="text-base font-semibold text-slate-900">Evidence Locker</h2>
            {evidence.length > 0 && (
              <span className="inline-flex items-center rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold text-slate-600">
                {evidence.length}
              </span>
            )}
          </div>
          <AnimatePresence>
            {showLockedAnim && (
              <motion.span
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.8 }}
                transition={{ duration: 0.3, ease: 'backOut' }}
                onAnimationComplete={() =>
                  setTimeout(() => setShowLockedAnim(false), 2000)
                }
                className="text-xs font-semibold text-emerald-600 flex items-center gap-1.5"
              >
                <Lock className="h-3.5 w-3.5" />
                Evidence locked in
              </motion.span>
            )}
          </AnimatePresence>
        </div>

        <div className="p-6 space-y-4">
          {/* Evidence list */}
          {evidence.length > 0 && (
            <motion.div
              className="space-y-2"
              initial="hidden"
              animate="visible"
              variants={{ visible: { transition: { staggerChildren: 0.06 } } }}
            >
              {evidence.map((item) => (
                <motion.div
                  key={item.id}
                  variants={evidenceItemVariants}
                  className="flex items-center gap-4 rounded-lg border border-slate-200 bg-slate-50 px-4 py-3"
                >
                  <FileIcon fileType={item.fileType} />
                  <div className="flex-1 min-w-0">
                    <p className="truncate text-sm font-medium text-slate-800">
                      {item.fileName}
                    </p>
                    <p className="text-xs text-slate-500">
                      {formatBytes(item.fileSizeBytes)} · Uploaded {formatDate(item.uploadedAt)}
                    </p>
                    {item.description && (
                      <p className="mt-0.5 text-xs text-slate-400">{item.description}</p>
                    )}
                  </div>
                  <a
                    href={item.storageUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={(e) => e.stopPropagation()}
                    className="flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-200 transition-colors"
                  >
                    <Download className="h-3.5 w-3.5" />
                    Download
                  </a>
                </motion.div>
              ))}
            </motion.div>
          )}

          {/* Dropzone */}
          <motion.div whileHover={{ scale: 1.005 }} whileTap={{ scale: 0.998 }}>
          <div
            {...getRootProps()}
            className={cn(
              'rounded-xl border-2 border-dashed p-8 text-center cursor-pointer transition-colors select-none',
              isDragActive
                ? 'border-brand-400 bg-brand-50 text-brand-700'
                : uploading
                  ? 'border-slate-200 bg-slate-50 text-slate-400 cursor-not-allowed'
                  : 'border-slate-200 bg-slate-50 text-slate-500 hover:border-brand-300 hover:bg-brand-50/40',
            )}
          >
            <input {...getInputProps()} />
            <div className="flex flex-col items-center gap-3">
              {uploading ? (
                <Loader2 className="h-8 w-8 animate-spin text-brand-500" />
              ) : (
                <Upload
                  className={cn(
                    'h-8 w-8 transition-colors',
                    isDragActive ? 'text-brand-500' : 'text-slate-400',
                  )}
                />
              )}
              <div>
                <p className="text-sm font-medium">
                  {uploading
                    ? 'Uploading…'
                    : isDragActive
                      ? 'Drop to upload'
                      : 'Drag & drop evidence here'}
                </p>
                {!uploading && (
                  <p className="mt-1 text-xs text-slate-400">
                    Images, PDFs, text files — max one file at a time
                  </p>
                )}
              </div>
              {!uploading && !isDragActive && (
                <span className="rounded-md border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-600 shadow-sm hover:bg-slate-50 transition-colors">
                  Browse files
                </span>
              )}
            </div>
          </div>
          </motion.div>
        </div>
      </motion.div>

      {/* Escalation Preview Dialog */}
      <EscalationPreviewDialog
        open={previewOpen}
        onOpenChange={setPreviewOpen}
        event={escalationDraft}
        onSend={handleSendEscalation}
      />
    </div>
  )
}
