import type { Client } from '../../types/client.types';

export const mockClients: Client[] = [
  {
    id: 'client_001',
    workspaceId: 'workspace_demo',
    name: 'Marcus Webb',
    email: 'marcus@acmecorp-demo.io',
    company: 'Acme Corp',
    industry: 'SaaS',
    country: 'US',
    riskScore: 82,
    riskLevel: 'high',
    totalInvoiced: 48000,
    totalOutstanding: 12400,
    paymentTermsDays: 30,
    averagePaymentDelay: 47,
    contractUrl: '/contracts/acme-2025.pdf',
    notes: 'Has disputed 2 previous invoices. Always pays eventually but requires escalation.',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2026-02-28'),
  },
  {
    id: 'client_002',
    workspaceId: 'workspace_demo',
    name: 'Priya Sharma',
    email: 'priya@brightlabs-demo.co',
    company: 'Bright Labs',
    industry: 'Design Agency',
    country: 'UK',
    riskScore: 23,
    riskLevel: 'low',
    totalInvoiced: 31000,
    totalOutstanding: 0,
    paymentTermsDays: 14,
    averagePaymentDelay: 3,
    notes: 'Pays within 3 days. Dream client.',
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'client_003',
    workspaceId: 'workspace_demo',
    name: 'Derek Holt',
    email: 'derek@vanishingact-demo.co',
    company: 'Vanishing Act LLC',
    industry: 'Entertainment',
    country: 'US',
    riskScore: 96,
    riskLevel: 'critical',
    totalInvoiced: 22000,
    totalOutstanding: 22000,
    paymentTermsDays: 30,
    averagePaymentDelay: 120,
    notes: 'CRITICAL: 120 days overdue. Legal demand sent. Do not start new work.',
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'client_004',
    workspaceId: 'workspace_demo',
    name: 'Sofia Mendes',
    email: 'sofia@techpulse-demo.com',
    company: 'TechPulse Agency',
    industry: 'Marketing',
    country: 'CA',
    riskScore: 41,
    riskLevel: 'medium',
    totalInvoiced: 18500,
    totalOutstanding: 3200,
    paymentTermsDays: 30,
    averagePaymentDelay: 18,
    notes: 'Usually pays but needs reminders. Good relationship overall.',
    createdAt: new Date('2025-04-10'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'client_005',
    workspaceId: 'workspace_demo',
    name: 'James Okafor',
    email: 'james@ghostmedia-demo.io',
    company: 'Ghost Media Inc.',
    industry: 'Entertainment',
    country: 'US',
    riskScore: 91,
    riskLevel: 'critical',
    totalInvoiced: 9500,
    totalOutstanding: 9500,
    paymentTermsDays: 14,
    averagePaymentDelay: 94,
    notes: 'No response to any contact. Small claims prep underway.',
    createdAt: new Date('2025-07-20'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'client_006',
    workspaceId: 'workspace_demo',
    name: 'Emma Thornton',
    email: 'emma@designstudio-demo.co',
    company: 'Thornton Design Studio',
    industry: 'Design Agency',
    country: 'UK',
    riskScore: 15,
    riskLevel: 'low',
    totalInvoiced: 42000,
    totalOutstanding: 0,
    paymentTermsDays: 7,
    averagePaymentDelay: 2,
    notes: 'Excellent client. Pays same day on most invoices.',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2026-02-28'),
  },
  {
    id: 'client_007',
    workspaceId: 'workspace_demo',
    name: 'Raj Patel',
    email: 'raj@infracore-demo.tech',
    company: 'InfraCore Systems',
    industry: 'Enterprise Tech',
    country: 'US',
    riskScore: 58,
    riskLevel: 'high',
    totalInvoiced: 75000,
    totalOutstanding: 15000,
    paymentTermsDays: 60,
    averagePaymentDelay: 35,
    notes: 'Net 60 terms mean slow payment is normal, but 35 days average delay is above benchmark.',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'client_008',
    workspaceId: 'workspace_demo',
    name: 'Claire Nguyen',
    email: 'claire@startuphub-demo.io',
    company: 'StartupHub Collective',
    industry: 'SaaS',
    country: 'CA',
    riskScore: 34,
    riskLevel: 'medium',
    totalInvoiced: 12000,
    totalOutstanding: 4000,
    paymentTermsDays: 30,
    averagePaymentDelay: 22,
    notes: 'Early-stage startup — cash flow sensitive. Invoice in smaller chunks if possible.',
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2026-02-10'),
  },
];
